### ISSUE TITLE
First/2nd/3rd winner -> Ranking

### ISSUE THREAD

**Issue by wolf128058** [leofonic/oxid_exclusive_deliverysets#1]
Is it possible to declare a first "winner" of deliverysets and if this one is not found,
we look for a second "winner" in list?

e.g.: If there is only one item in basket demanding a delivery by "truck company" this type of delivery is the "winner".
But without one single truck-item we look for parcel-items next.
If there is one single parcel-item this delivery-type wins:

And finally
baskets without any candidates for the first-and second winner are handled with all the other deliverysets.

As I remember you can put a list of winners in the backend-options of this module,
but there is/was no type of ranking amongst them.

Ist that still correct?
Or is Ranking possible by now.

**Comment by leofonic** [comment]
Thank you, i will look at this.

**Comment by wolf128058** [comment]
Hello Frank,

any news about that issue?
We need this feature, because we are looking after an OXID that uses this module
and in this Shop we would like to introduce a third type of delivery.

Of course we do not expect all your work for free.
I would also be pleased receiving an offer from you.

Kind regards
Jonas

**Comment by wolf128058** [comment]
Seems like this feature is created with 6c69a945bab90dde22b79b7c61d3efe4ee593d10.
⮱ I close that issue.
