### ISSUE TITLE
Login & Internal Server Error

### ISSUE THREAD

**Issue by wolf128058** [leofonic/oxid_exclusive_deliverysets#2]
Mein Kollege hat da ein unangenehmes Problem entdeckt, 
was uns seit dem 30.08. auch dazu bewegt hat, die alte Version des Moduls zu verwenden:

> Sobald ein Artikel der per Spedition versendet wird in den Warenkorb gelegt wird, kann man sich in der Kasse nicht mehr einloggen.
> Nach ca. 30sek Ladezeit bekommt man einen internal Server Error.

Zum Verständnis:
- "Spedition" wäre die Versandart, die den Warenkorb im Falle von mehreren Versandarten  gewinnen sollte. (Gewinnt in dem Falle vor dem Paketversand)
- Wir wollten als immer mit angebotene Versandart die "Selbstabholung" mit ins Rennen werfen und bekommen das so natürlich immer noch nicht hin.

**Comment by leofonic** [comment]
Bug ist gefixt, können Sie mir eine kurze Rückmeldung geben ob das Problem damit behoben ist?

**Comment by wolf128058** [comment]
Danke, werd ich gleich testen.

**Comment by wolf128058** [comment]
funktioniert.
